export const KEY_FIELDS = [
  {
    group: "IA",
    items: [
      {
        id: "llmProvider",
        label: "Provider texte (LLM)",
        help: "Ollama = local, 0 token cloud. Gemini reste utile pour images / Veo / écoute audio.",
        required: false,
        inputType: "select",
        options: [
          { value: "gemini", label: "Gemini (cloud)" },
          { value: "ollama", label: "Ollama (local)" },
        ],
      },
      {
        id: "ollamaBaseUrl",
        label: "URL Ollama",
        placeholder: "http://127.0.0.1:11434",
        help: "Doit être joignable depuis le serveur Astro (souvent localhost en dev).",
        required: false,
        inputType: "url",
        when: { llmProvider: "ollama" },
        url: "https://ollama.com/",
      },
      {
        id: "ollamaModel",
        label: "Modèle Ollama",
        placeholder: "llama3.2",
        help: "Ex. llama3.2, mistral, qwen2.5 — `ollama pull <modèle>` puis Tester.",
        required: false,
        inputType: "text",
        when: { llmProvider: "ollama" },
      },
      {
        id: "geminiApiKey",
        label: "Gemini API Key",
        placeholder: "AIza...",
        help: "Requis si provider = Gemini. Aussi pour images Gemini, Veo et analyse audio.",
        required: false,
        url: "https://aistudio.google.com/apikey",
      },
      {
        id: "geminiModel",
        label: "Modèle Gemini",
        placeholder: "gemini-2.5-flash-lite",
        help: "1.5 / 2.0 sont retirés par Google — 2.5-flash-lite recommandé (free tier)",
        required: false,
        inputType: "select",
        when: { llmProvider: "gemini" },
        options: [
          { value: "gemini-2.5-flash-lite", label: "2.5 Flash Lite (free, recommandé)" },
          { value: "gemini-2.5-flash", label: "2.5 Flash (free)" },
          { value: "gemini-flash-lite-latest", label: "Flash Lite (alias latest)" },
          { value: "gemini-flash-latest", label: "Flash (alias latest)" },
        ],
      },
      {
        id: "videoProvider",
        label: "Provider vidéo (clips)",
        help: "Wan2GP = local GPU Pinokio. Veo/Seedance restent dispo dans l’étape Clip.",
        required: false,
        inputType: "select",
        options: [
          { value: "cloud", label: "Cloud (Veo / Seedance dans Clip)" },
          { value: "wan2gp", label: "Wan2GP (local Pinokio)" },
        ],
      },
      {
        id: "wan2gpBaseUrl",
        label: "URL Wan2GP",
        placeholder: "http://10.1.0.88:PORT",
        help: "URL Home Server Pinokio de Wan2GP. Dans l’UI Wan2GP : modèle t2v chargé. sonozz envoie Start Image (I2V) + queue Gradio.",
        required: false,
        inputType: "url",
        when: { videoProvider: "wan2gp" },
        url: "https://github.com/deepbeepmeep/Wan2GP",
      },
    ],
  },
  {
    group: "Morceaux",
    items: [
      {
        id: "musicProvider",
        label: "Générateur de morceaux",
        help: "ACE-Step = local (voix + toutes langues). SongGen = local (EN/ZH). MiniMax = cloud Replicate.",
        required: false,
        inputType: "select",
        options: [
          { value: "acestep", label: "ACE-Step Studio (local)" },
          { value: "replicate", label: "Replicate MiniMax 2.6 (cloud)" },
          { value: "songgen", label: "SongGeneration Studio (local)" },
        ],
      },
      {
        id: "aceStepBaseUrl",
        label: "URL ACE-Step Studio",
        placeholder: "https://ace.briseteia.me",
        help: "Express ACE (:8001 / tunnel). Gradio Python tourne en :7865 sur Demeter. LAN : http://10.1.0.88:8001",
        required: false,
        inputType: "url",
        url: "https://github.com/timoncool/ACE-Step-Studio",
      },
      {
        id: "aceStepPreferredModel",
        label: "Modèle ACE-Step",
        help: "DiT Gradio uniquement (Turbo / SFT / BF16). Merge dans l’UI Pinokio n’est pas un vrai DiT.",
        required: false,
        inputType: "select",
        options: [
          { value: "", label: "Auto (modèle déjà chargé)" },
          { value: "acestep-v15-xl-turbo", label: "XL Turbo (8 steps, rapide)" },
          { value: "acestep-v15-xl-sft", label: "XL SFT (50 steps, qualité)" },
          { value: "acestep-v15-xl-turbo-bf16", label: "XL Turbo BF16 (compact)" },
          { value: "marcorez8/acestep-v15-xl-turbo-bf16", label: "XL Turbo BF16 (HF)" },
        ],
      },
      {
        id: "songGenBaseUrl",
        label: "URL SongGeneration Studio",
        placeholder: "http://10.1.0.88:42014",
        help: "Doit être joignable depuis le serveur Astro. Ex. Home Server Pinokio sur Demeter.",
        required: false,
        inputType: "url",
        url: "https://github.com/BazedFrog/SongGeneration-Studio",
      },
      {
        id: "replicateApiToken",
        label: "Replicate API Token",
        placeholder: "r8_...",
        help: "MiniMax (si générateur = Replicate). Aussi images Flux et Seedance. Billing recommandé.",
        required: false,
        url: "https://replicate.com/account/api-tokens",
      },
    ],
  },
  {
    group: "Streaming",
    items: [
      {
        id: "spotifyClientId",
        label: "Spotify Client ID",
        placeholder: "abc123...",
        help: "App Spotify Developer",
        required: false,
        url: "https://developer.spotify.com/dashboard",
      },
      {
        id: "spotifyClientSecret",
        label: "Spotify Client Secret",
        placeholder: "secret...",
        help: "Pour token client + analyse catalogue",
        required: false,
      },
      {
        id: "spotifyRefreshToken",
        label: "Spotify Refresh Token",
        placeholder: "AQ...",
        help: "Optionnel — création playlist sur ton compte",
        required: false,
      },
      {
        id: "deezerAppId",
        label: "Deezer App ID",
        placeholder: "optionnel",
        help: "Charts Deezer publics sans clé ; ID pour usage avancé",
        required: false,
        url: "https://developers.deezer.com/",
      },
    ],
  },
  {
    group: "Distribution ONCE",
    items: [
      {
        id: "onceApiToken",
        label: "ONCE Personal Access Token",
        placeholder: "once_pat_...",
        help: "Obligatoire pour publier automatiquement → Spotify. Account → Developer → Create token",
        required: false,
        url: "https://once.app/",
      },
      {
        id: "distrokidArtistName",
        label: "Nom d'artiste (exact stores)",
        placeholder: "Identique à Spotify for Artists",
        help: "Doit matcher exactement l'artiste existant si déjà créé",
        required: false,
        inputType: "text",
      },
      {
        id: "distrokidLegalName",
        label: "Nom légal writer (prénom + nom)",
        placeholder: "Kaelen Moreau",
        help: "Obligatoire pour ONCE si l'artiste est un mononyme. Ex. « Kaelen Moreau ».",
        required: false,
        inputType: "text",
      },
      {
        id: "distrokidProducerName",
        label: "Nom de producteur",
        placeholder: "Ex. Studio Sonozz / Alex Dupont",
        help: "Crédit Producer (et Engineer) appliqué à tous les artistes / releases ONCE. Si vide → nom légal writer.",
        required: false,
        inputType: "text",
      },
      {
        id: "distrokidLabel",
        label: "Label / copyright",
        placeholder: "Ex. ton nom / ton imprint",
        help: "Record label + © ℗ sur TOUTES les releases ONCE. À l’enregistrement, forcé aussi sur tous les profils artistes existants. Releases déjà soumises : republier (même release) pour mettre à jour le draft ONCE.",
        required: false,
        inputType: "text",
      },
      {
        id: "distrokidReleaseDays",
        label: "Délai sortie (jours)",
        placeholder: "14",
        help: "Date de sortie = aujourd'hui + N jours (min. recommandé 7–14)",
        required: false,
        inputType: "number",
      },
    ],
  },
  {
    group: "Réseaux",
    items: [
      {
        id: "tiktokClientKey",
        label: "TikTok Client Key",
        placeholder: "aw…",
        help: "Fourni par TikTok Developers (souvent aw…). Pas le Client Secret. Login Kit doit être ajouté à l’app.",
        required: false,
        url: "https://developers.tiktok.com/",
        inputType: "text",
      },
      {
        id: "tiktokClientSecret",
        label: "TikTok Client Secret",
        placeholder: "…",
        help: "Secret de l’app. Enregistre, puis Connecter TikTok. Localhost = Login Kit Desktop ; prod = Login Kit Web (HTTPS).",
        required: false,
      },
      {
        id: "tiktokAccessToken",
        label: "TikTok Access Token",
        placeholder: "rempli automatiquement après OAuth",
        help: "Résultat de « Reconnecter ». Doit inclure video.publish (Direct Post).",
        required: false,
      },
      {
        id: "tiktokRefreshToken",
        label: "TikTok Refresh Token",
        placeholder: "rempli automatiquement après OAuth",
        help: "Permet de renouveler l’access token (~24 h). Rempli par « Connecter TikTok ».",
        required: false,
      },
      {
        id: "tiktokPrivacyLevel",
        label: "Visibilité TikTok (Direct Post)",
        help: "App non auditée : « Uniquement moi ». Public = audit app requis. Compte TikTok privé parfois obligatoire pour Direct Post.",
        required: false,
        inputType: "select",
        options: [
          { value: "SELF_ONLY", label: "Uniquement moi (recommandé sans audit)" },
          { value: "MUTUAL_FOLLOW_FRIENDS", label: "Amis (follow mutuel)" },
          { value: "FOLLOWER_OF_CREATOR", label: "Abonnés" },
          { value: "PUBLIC_TO_EVERYONE", label: "Public (nécessite audit app)" },
        ],
      },
      {
        id: "tiktokPostMode",
        label: "Mode publication TikTok",
        help: "Direct = profil tout de suite. Inbox = brouillon à valider dans l’app. Auto = Direct, puis Inbox si TikTok bloque (app non auditée).",
        required: false,
        inputType: "select",
        options: [
          { value: "direct", label: "Direct Post (profil) — recommandé" },
          { value: "auto", label: "Auto (Direct seulement ; pas d’Inbox auto)" },
          { value: "inbox", label: "Inbox (brouillon — max ~5 / 24 h)" },
        ],
      },
      {
        id: "youtubeClientId",
        label: "YouTube Client ID",
        placeholder: "….apps.googleusercontent.com",
        help: "Google Cloud → Identifiants → OAuth 2.0 (Application Web). Active YouTube Data API v3.",
        required: false,
        url: "https://console.cloud.google.com/apis/credentials",
        inputType: "text",
      },
      {
        id: "youtubeClientSecret",
        label: "YouTube Client Secret",
        placeholder: "GOCSPX-…",
        help: "Secret OAuth de l’app Web. Enregistre, puis Connecter YouTube.",
        required: false,
      },
      {
        id: "youtubeAccessToken",
        label: "YouTube Access Token",
        placeholder: "rempli automatiquement après OAuth",
        help: "Résultat de « Connecter YouTube ». Expire ~1 h — renouvelé via refresh token.",
        required: false,
      },
      {
        id: "youtubeRefreshToken",
        label: "YouTube Refresh Token",
        placeholder: "rempli automatiquement après OAuth",
        help: "Permet de renouveler l’access token. Rempli par « Connecter YouTube ».",
        required: false,
      },
      {
        id: "youtubePrivacyStatus",
        label: "Visibilité YouTube Shorts",
        help: "Privé recommandé en test. Public nécessite souvent un projet Google vérifié + canal YouTube en règle.",
        required: false,
        inputType: "select",
        options: [
          { value: "private", label: "Privé (recommandé en test)" },
          { value: "unlisted", label: "Non listé" },
          { value: "public", label: "Public" },
        ],
      },
      {
        id: "socialWebhookUrl",
        label: "Webhook diffusion (Activepieces / Make)",
        placeholder: "https://cloud.activepieces.com/api/v1/webhooks/...",
        help: "POST auto du short + caption pour Instagram Reels / multi-réseaux (YouTube & TikTok ont une intégration native).",
        required: false,
        inputType: "url",
      },
    ],
  },
];
